name: 问题反馈 Bug report
description: 程序出现问题
labels: ['bug']
body:
  - type: checkboxes
    id: shallcheck
    attributes:
      label: 应该确定的
      options:
      - label: 已尝试使用搜索引擎，且不能解决我的问题 | I have google it and can hardly find any solution.
        required: true
      - label: 我填写的标题意义明确，而不是“一个建议”、“卡住了”,"LALC无法运行"等 | The title is clear rather than "A advice", "LALC stuck!".
        required: true
      - label:  我已确认目前没有类似 issue | I have confirmed that there is no similar issue at this time. 
        required: true
      - label: 我使用的程序版本已为最新版 | The programme is the latest version.
        required: true
      - label: 我已完整查看过项目 README，尤其是常见问题部分 | I have reviewed the project README in its entirety, especially the FAQ section
        required: true
      - label: 我理解并愿意跟进此 issue，协助测试和提供反馈 | I understand and am willing to follow up on this issue, assist with testing and provide feedback.
        required: true
      - label: 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭 | I understand and agree with the above, and understand that project maintainers have limited energy, and that issues that don't follow the rules may be ignored or simply shut down
        required: true
  - type: textarea
    id: describe
    attributes:
      label: 问题描述
      description: 尽可能详细描述你的问题
    validations:
      required: true
  - type: textarea
    id: rebug
    attributes:
      label: 重现问题
      description: 描述一个可重复的步骤，复现你的问题
    validations:
      required: true
  - type: textarea
    id: log
    attributes:
      label: 日志文件
      description: 上传log文件夹下所有.log文件
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: 视频/截图
      description: 上传你发生此问题时的视频/截图
    validations:
      required: false
  - type: textarea
    id: shouldbe
    attributes:
      label: 应该是？
      description: 描述你认为应为的实际效果
    validations:
      required: false
  - type: textarea
    id: others
    attributes:
      label: 其他信息
      description: |
        你最好提供以下内容：
        操作系统、语言及版本号；屏幕分辨率；软件版本号等。
    validations:
      required: false
