name: mirrorchyan-release-note

on:
  workflow_dispatch:
  release:
    types: [edited]

jobs:
  mirrorchyan:
    runs-on: macos-latest

    steps:
      - id: uploading
        uses: MirrorChyan/release-note-action@v1
        with:
          mirrorchyan_rid: LALC

          upload_token: ${{ secrets.MIRRORCHYANUPLOADTOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
